name: my_portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  animated_splash_screen: ^1.3.0
  audioplayers: ^6.0.0
  carousel_slider: ^4.2.1
  curved_navigation_bar: ^1.0.5
  draggable_fab: ^0.1.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  path_provider: ^2.1.3
  swipe_deck: ^1.1.0
  url_launcher: ^6.2.6
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/audio/
